- 1.1.16+202510301932
- _NAME: MX Master 3S
  _modelId: B03400000000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 3B799EB1
  _unitId: 3B799EB1
  _wpid: B034
  change-host: null
  divert-keys: { 82: 0, 83: 0, 86: 0, 195: 0, 196: 0 }
  dpi: 1000
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys:
    { 80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196 }
  scroll-ratchet: 2
  smart-shift: 10
  thumb-scroll-invert: false
  thumb-scroll-mode: false
- _NAME: MX Keys for Business
  _modelId: B38000000000
  _sensitive:
    {
      backlight: false,
      backlight_level: true,
      disable-keyboard-keys: ignore,
      divert-keys: true,
      multiplatform: false,
    }
  _serial: 149F82FB
  _unitId: 149F82FB
  _wpid: B380
  backlight: 255
  backlight_duration_hands_in: 30
  backlight_duration_hands_out: 15
  backlight_duration_powered: 300
  backlight_level: 0
  change-host: null
  disable-keyboard-keys: { 1: false, 2: false, 4: false, 8: false, 16: false }
  divert-keys:
    {
      10: 0,
      111: 1,
      199: 0,
      200: 0,
      226: 0,
      227: 0,
      228: 0,
      229: 0,
      230: 0,
      231: 0,
      232: 0,
      233: 0,
      234: 0,
      259: 0,
      264: 1,
      266: 1,
      284: 1,
    }
  fn-swap: true
  multiplatform: 0
- _NAME: MX Master 3S For Business
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight,
    backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control,
    rgb_zone_, brightness_control, per-key-lighting, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys,
    m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B03500000000
  _serial: D3A52139
  _unitId: D3A52139
  _wpid: B035
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 0, 196: 0}
  dpi: 1000
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  scroll-ratchet: 2
  smart-shift: 10
  thumb-scroll-invert: false
  thumb-scroll-mode: false
- _NAME: MX Keys Mini for Business
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, dpi_extended, speed-change, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting,
    reprogrammable-keys, persistent-remappable-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert,
    gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B36E00000000
  _sensitive: {multiplatform: false}
  _serial: 35084CCB
  _unitId: 35084CCB
  _wpid: B36E
  backlight: 0
  change-host: null
  disable-keyboard-keys: {1: false, 8: false, 16: false}
  divert-keys: {226: 0, 227: 0, 229: 0, 231: 0, 232: 0, 233: 0, 259: 0, 264: 0, 266: 0, 279: 0, 284: 0}
  fn-swap: true
  multiplatform: 0
